language: node_js
node_js:
- stable
deploy:
  provider: heroku  
  app:
    name: buckeatlist
  on:
    repo: davidgeht/untitled-project2    
  api_key:
    secure: XvjAgrafH38Ac4PPn7nPdT9o5u3i9XqHiwicRfPr3gx/+dWup5J0HUxC5L5lWtSuJZgszZHfirNd3b4QLUCwhnKcllBDYFABhhjC0rCekG6L15x6SvXadjZ3TtDcqGugtSREOZ+osZCEHJU8mTrUgMTz+n4srB0DTfjsvkfn+PZmVjLo9TMCul0lNDSM25YboYHtM2NfGxLTHfk8/Wl6y3VXzU6YyX9Aorz1RZjbDJEnsi4yNOlOXunPd2O32K8v3jU75uIvixc6xmyWicKGsvlVfIA/pD7pKE7zzG7BiO+JcOsOoTbGKrxDzSHt2p9PhNsY8pfpVRQIKGrwcGOfxtdBnKQIh4KN2Y8spPiGn2Xpf+uef3kxocERxa1hPX8KrUtj+5H5uHzqmNhhdZaa9RnSwCdUHoIIKM1uM+m/UgzmSy4tRhGcpCsvFXFCllYzMBdskce8Be4+rg4FKROusNfApWDjNqlx0DvJbHeER5gJ9fvR+RAbc6R2Zv1Ufk0jfmOIkNu6FB6LodP0/gUsTWwyUq67hrRymeOqxaYxyefG9W6CPgUXzaaUwkJU3E+a3HRMj+6chJhmRr621WouJdxGLFFC4VawW2QWAwihuYF46Bba9B3MOBYvUQXC+2M8AN3atFQT69N1531iiZrNDUqoIEOoFchaPDNs3Av3zOw=
