language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: buckeatlist
  on:
    repo: davidgeht/untitled-project2
    branch: master
  api_key:
    secure: I+qqmgrIYzNxtFCzLWlS7ZW0SyYerzb8cIrTPWBsmKt5JztdojjO7YzNLb4PZC9t8TuLce1QLxsvCXqNnMp5B6SSPuelFwp3ppD54kOduOFYSwcBKi1UbZ3op2ORnRw7esrRVN6pyM2mrrzBqANa71QCifW1+H8MnfSkF/LNYpqNK/PtwPlKpvBas05id72gyiQfPvx//oWXwUwtGp3QtSWE2oxTHqg1kav0SHU1U3vK1peDJGzoETdcJxeJ1wjnGM/ZwmoFVCYB3fLzl6hsDoL22ARCnDLiwu1+Ye6p9fxBYOJ4ViCi0kK+1isAgeMPz3EsBQfjMU2diT/42bJ4FOTgBembzYSidS1PxThmbqf5XLI2G1YhgCvTdqDd9si6GxpREMfGiXHUTvEvff4u91aCxsdLkqUOEyvvTOr7FTRdtNFs03aA5GfPekzYexxiEuybIE0tAr2OJwDI3/zdFEhIkyvyx4eyWXLUvhLPuQAiYGLzifSTtaCYIYJNmK8eHp3tj7VJBqpmGEhImBF3bOVnspB+ThVnMV28vKqEVnoH7TbkhC9bFXLldoqDiQQx4Xx1w43SQeSd4pNXexikQJvJ8g21KYlvMj9oiOs9MFvNRvRY60Y4YsK0zzKqX+Zza64ykX9s2nY5DSxXbdn/ZrftgyD/WA31LSOsLrL3w60=
